//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commute.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commute.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://s3-eu-west-1.amazonaws.com/commute/Pictures/.
        /// </summary>
        public static string Amazon_picture_HTTP {
            get {
                return ResourceManager.GetString("Amazon picture HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commute.
        /// </summary>
        public static string Application_name {
            get {
                return ResourceManager.GetString("Application name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string Create_account {
            get {
                return ResourceManager.GetString("Create account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Images/Upload/.
        /// </summary>
        public static string Dir_image_upload {
            get {
                return ResourceManager.GetString("Dir image upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        public static string Error_database_access {
            get {
                return ResourceManager.GetString("Error database access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already exists.
        /// </summary>
        public static string Error_duplicate_account {
            get {
                return ResourceManager.GetString("Error duplicate account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not look like a valid mail address.
        /// </summary>
        public static string Error_invalid_mail {
            get {
                return ResourceManager.GetString("Error invalid mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is too long.
        /// </summary>
        public static string Error_string_too_long {
            get {
                return ResourceManager.GetString("Error string too long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account does not exists.
        /// </summary>
        public static string Error_unknown_account {
            get {
                return ResourceManager.GetString("Error unknown account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password, did you forget it...too bad !.
        /// </summary>
        public static string Error_wrong_password {
            get {
                return ResourceManager.GetString("Error wrong password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new location.
        /// </summary>
        public static string Location_create {
            get {
                return ResourceManager.GetString("Location create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        public static string Location_name {
            get {
                return ResourceManager.GetString("Location name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Location_type {
            get {
                return ResourceManager.GetString("Location type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update location.
        /// </summary>
        public static string Location_update {
            get {
                return ResourceManager.GetString("Location update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map below shows our two routes:.
        /// </summary>
        public static string Mail_contact_map {
            get {
                return ResourceManager.GetString("Mail contact map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This map is just a picture. Click the map to view it as a Goole map in Commute..
        /// </summary>
        public static string Mail_contact_map_title {
            get {
                return ResourceManager.GetString("Mail contact map title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have found that our commute routes are quite similar, can we get in touch to see if we can commute togther ?.
        /// </summary>
        public static string Mail_contact_msg {
            get {
                return ResourceManager.GetString("Mail contact msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just reply to this mail to contact me (you will see my mail address)..
        /// </summary>
        public static string Mail_contact_reply {
            get {
                return ResourceManager.GetString("Mail contact reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have matching routes.
        /// </summary>
        public static string Mail_contact_title {
            get {
                return ResourceManager.GetString("Mail contact title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been sucessfuly created. &lt;p&gt;You can now register routes and find commuters with similar routes as yours.&lt;/p&gt;.
        /// </summary>
        public static string Mail_welcome_created {
            get {
                return ResourceManager.GetString("Mail welcome created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register issues, ask for help, request features use the.
        /// </summary>
        public static string Mail_welcome_forum {
            get {
                return ResourceManager.GetString("Mail welcome forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish you a safe and fun commute, the Commute Team..
        /// </summary>
        public static string Mail_welcome_safe_commute {
            get {
                return ResourceManager.GetString("Mail welcome safe commute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, read the.
        /// </summary>
        public static string Mail_welcome_start {
            get {
                return ResourceManager.GetString("Mail welcome start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Commute !.
        /// </summary>
        public static string Mail_welcome_welcome {
            get {
                return ResourceManager.GetString("Mail welcome welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is mandatory.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your car to commute between home and work with others or find a car in your area to commute to work. Going to work can be fun: Save fuel, save money and make new friends to share a happy time when commuting. This is the green way to go to work. Help saving the planet. Reduce gaz emission.
        /// </summary>
        public static string Metadesc_default {
            get {
                return ResourceManager.GetString("Metadesc default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Commute the green and friendly way to commute. Find routes in your area. Get started with Commute. Joint Commute community..
        /// </summary>
        public static string Metadesc_home_welcome {
            get {
                return ResourceManager.GetString("Metadesc home welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the list of route you have defined. You can update the route. You can search route which are close match to your route. You can create new route..
        /// </summary>
        public static string Metadesc_route_list {
            get {
                return ResourceManager.GetString("Metadesc route list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default map location when creating new route. Commute is a friendly and green way to commute between home and work..
        /// </summary>
        public static string Metadesc_user_setlocation {
            get {
                return ResourceManager.GetString("Metadesc user setlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mail will be sent to the other user with your mail.&lt;div&gt;Do you agree ?&lt;/div&gt;.
        /// </summary>
        public static string Msg_confirm_mail_sending {
            get {
                return ResourceManager.GetString("Msg confirm mail sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is.
        /// </summary>
        public static string My_name {
            get {
                return ResourceManager.GetString("My name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record does not exists.
        /// </summary>
        public static string No_record {
            get {
                return ResourceManager.GetString("No record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Password_confirm {
            get {
                return ResourceManager.GetString("Password confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick start guide.
        /// </summary>
        public static string Quick_start_guide {
            get {
                return ResourceManager.GetString("Quick start guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create route.
        /// </summary>
        public static string Route_create {
            get {
                return ResourceManager.GetString("Route create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update route.
        /// </summary>
        public static string Route_create_update {
            get {
                return ResourceManager.GetString("Route create update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route no.
        /// </summary>
        public static string Route_id {
            get {
                return ResourceManager.GetString("Route id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My routes.
        /// </summary>
        public static string Route_list {
            get {
                return ResourceManager.GetString("Route list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New route.
        /// </summary>
        public static string Route_new {
            get {
                return ResourceManager.GetString("Route new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search route.
        /// </summary>
        public static string Route_search {
            get {
                return ResourceManager.GetString("Route search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View route.
        /// </summary>
        public static string Route_view {
            get {
                return ResourceManager.GetString("Route view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek.
        /// </summary>
        public static string Seek {
            get {
                return ResourceManager.GetString("Seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update account.
        /// </summary>
        public static string Update_account {
            get {
                return ResourceManager.GetString("Update account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data.
        /// </summary>
        public static string Update_data {
            get {
                return ResourceManager.GetString("Update data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update picture.
        /// </summary>
        public static string Update_picture {
            get {
                return ResourceManager.GetString("Update picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account.
        /// </summary>
        public static string User_account {
            get {
                return ResourceManager.GetString("User account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login.
        /// </summary>
        public static string User_login {
            get {
                return ResourceManager.GetString("User login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logout.
        /// </summary>
        public static string User_logout {
            get {
                return ResourceManager.GetString("User logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration.
        /// </summary>
        public static string User_registration {
            get {
                return ResourceManager.GetString("User registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set location.
        /// </summary>
        public static string User_set_location {
            get {
                return ResourceManager.GetString("User set location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now update data (upload picture) on your account.
        /// </summary>
        public static string Welcome_account {
            get {
                return ResourceManager.GetString("Welcome account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the quick start documentation to have an overview of Commute features..
        /// </summary>
        public static string Welcome_help {
            get {
                return ResourceManager.GetString("Welcome help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, create an account to join Commute community.
        /// </summary>
        public static string Welcome_join {
            get {
                return ResourceManager.GetString("Welcome join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just sent you a welcome mail with more instructions at your address: .
        /// </summary>
        public static string Welcome_mail {
            get {
                return ResourceManager.GetString("Welcome mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Commute, the green and friendly way to commute.
        ///&lt;div&gt;- Define the commute routes you seek/offer&lt;/div&gt;
        ///&lt;div&gt;- Find other commuters with similar route&lt;/div&gt;
        ///&lt;div&gt;- Get in touch with them to commute together&lt;/div&gt;
        ///&lt;div&gt;- Keep track of the expenses to share&lt;/div&gt;.
        /// </summary>
        public static string Welcome_message {
            get {
                return ResourceManager.GetString("Welcome message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to Commute community..
        /// </summary>
        public static string Welcome_registred {
            get {
                return ResourceManager.GetString("Welcome registred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And then your are ready to define your first commute route.
        /// </summary>
        public static string Welcome_route {
            get {
                return ResourceManager.GetString("Welcome route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your default location.
        /// </summary>
        public static string Welcome_set_location {
            get {
                return ResourceManager.GetString("Welcome set location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatively, you can view available routes for your commute path witout creating an account..
        /// </summary>
        public static string Welcome_view_route {
            get {
                return ResourceManager.GetString("Welcome view route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm.
        /// </summary>
        public static string Wtitle_confirmation {
            get {
                return ResourceManager.GetString("Wtitle confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account.
        /// </summary>
        public static string Your_account {
            get {
                return ResourceManager.GetString("Your account", resourceCulture);
            }
        }
    }
}
