//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commute.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commute.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account does not exist in Phonebook.
        /// </summary>
        public static string Account_not_in_Phonebook {
            get {
                return ResourceManager.GetString("Account not in Phonebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to this car.
        /// </summary>
        public static string Added_to_car {
            get {
                return ResourceManager.GetString("Added to car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in this car.
        /// </summary>
        public static string Already_in_car {
            get {
                return ResourceManager.GetString("Already in car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commute.
        /// </summary>
        public static string Application_name {
            get {
                return ResourceManager.GetString("Application name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection agenda.
        /// </summary>
        public static string Connection_agenda {
            get {
                return ResourceManager.GetString("Connection agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection not found.
        /// </summary>
        public static string Connection_not_found {
            get {
                return ResourceManager.GetString("Connection not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now a driver, drive safe.
        /// </summary>
        public static string Driver_created {
            get {
                return ResourceManager.GetString("Driver created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver removed from connection.
        /// </summary>
        public static string Driver_deleted {
            get {
                return ResourceManager.GetString("Driver deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already the driver for this connection.
        /// </summary>
        public static string Driver_for_this_connection {
            get {
                return ResourceManager.GetString("Driver for this connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the driver for this connection, not a passenger.
        /// </summary>
        public static string Driver_not_passenger {
            get {
                return ResourceManager.GetString("Driver not passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now the driver.
        /// </summary>
        public static string Driver_updated {
            get {
                return ResourceManager.GetString("Driver updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        public static string Error_database_access {
            get {
                return ResourceManager.GetString("Error database access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 2 locations are the same.
        /// </summary>
        public static string Location_are_the_same {
            get {
                return ResourceManager.GetString("Location are the same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new location.
        /// </summary>
        public static string Location_create {
            get {
                return ResourceManager.GetString("Location create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name.
        /// </summary>
        public static string Location_name {
            get {
                return ResourceManager.GetString("Location name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Location_type {
            get {
                return ResourceManager.GetString("Location type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update location.
        /// </summary>
        public static string Location_update {
            get {
                return ResourceManager.GetString("Location update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is mandatory.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record does not exists.
        /// </summary>
        public static string No_record {
            get {
                return ResourceManager.GetString("No record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from this car.
        /// </summary>
        public static string Removed_from_car {
            get {
                return ResourceManager.GetString("Removed from car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the maximum number of passengers you can drive (driver not included).
        /// </summary>
        public static string Specify_seat_in_car {
            get {
                return ResourceManager.GetString("Specify seat in car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated time.
        /// </summary>
        public static string Time_updated {
            get {
                return ResourceManager.GetString("Time updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
